SELECT 
    NROCTA.ctabnro AS NROCTA,
    banco.errazsoc AS banco,
    FORMAPAGO.fpagdescabr AS FORMAPAGO,
    PERIODO.pliqdesc AS PERIODO,
    PUENTELIQEMPLEADO.ternro AS PUENTELIQEMPLEADO,
    PUENTECABLIQ.cliqnro AS PUENTECABLIQ,
    EMPLEADOLIQ.empleg AS EMPLEADOLIQ,
    CONCCANTIDAD.dlicant AS CONCCANTIDAD,
    CONCCANTIDAD1.dlicant AS CONCCANTIDAD1,
    CONCCANTIDAD2.dlicant AS CONCCANTIDAD2,
    CONMONTO2.dlimonto AS CONMONTO2,
    CONCCANTIDAD3.dlicant AS CONCCANTIDAD3,
    PUENTEDETLIQ.cliqnro AS PUENTEDETLIQ,
    CONMONTO.dlimonto AS CONMONTO,
    CONMONTO1.dlimonto AS CONMONTO1,
    PUENTEDETLIQACUM.cliqnro AS PUENTEDETLIQACUM,
    ACUMONTO.almonto AS ACUMONTO,
    ACUCANTIDAD.alcant AS ACUCANTIDAD,
    ACUCANTIDAD1.alcant AS ACUCANTIDAD1,
    ACUCANTIDAD2.alcant AS ACUCANTIDAD2,
    ACUCANTIDAD3.alcant AS ACUCANTIDAD3,
    ACUMONTO1.almonto AS ACUMONTO1,
    ACUMONTO2.almonto AS ACUMONTO2,
    ACUMONTO3.almonto AS ACUMONTO3
FROM 
    ctabancaria NROCTA
JOIN 
    tercero banco ON PUENTELIQEMPLEADO.ternro = banco.ternro
JOIN 
    formapago FORMAPAGO ON PUENTEDETLIQ.cliqnro = FORMAPAGO.cliqnro
JOIN 
    periodo PERIODO ON PUENTECABLIQ.cliqnro = PERIODO.cliqnro
JOIN 
    v_empleado EMPLEADOLIQ ON EMPLEADOLIQ.empleg = EMPLEADOLIQ.empleg
JOIN 
    detliq CONCCANTIDAD ON CONCCANTIDAD.dlicant = CONCCANTIDAD.dlicant
JOIN 
    detliq CONCCANTIDAD1 ON CONCCANTIDAD1.dlicant = CONCCANTIDAD1.dlicant
JOIN 
    detliq CONCCANTIDAD2 ON CONCCANTIDAD2.dlicant = CONCCANTIDAD2.dlicant
JOIN 
    detliq CONMONTO2 ON CONMONTO2.dlimonto = CONMONTO2.dlimonto
JOIN 
    detliq CONCCANTIDAD3 ON CONCCANTIDAD3.dlicant = CONCCANTIDAD3.dlicant
JOIN 
    detliq PUENTEDETLIQ ON PUENTEDETLIQ.cliqnro = PUENTEDETLIQ.cliqnro
JOIN 
    detliq CONMONTO ON CONMONTO.dlimonto = CONMONTO.dlimonto
JOIN 
    detliq CONMONTO1 ON CONMONTO1.dlimonto = CONMONTO1.dlimonto
JOIN 
    acu_liq PUENTEDETLIQACUM ON PUENTEDETLIQACUM.cliqnro = PUENTEDETLIQACUM.cliqnro
JOIN 
    acu_liq ACUMONTO ON ACUMONTO.almonto = ACUMONTO.almonto
JOIN 
    acu_liq ACUCANTIDAD ON ACUCANTIDAD.alcant = ACUCANTIDAD.alcant
JOIN 
    acu_liq ACUCANTIDAD1 ON ACUCANTIDAD1.alcant = ACUCANTIDAD1.alcant
JOIN 
    acu_liq ACUCANTIDAD2 ON ACUCANTIDAD2.alcant = ACUCANTIDAD2.alcant
JOIN 
    acu_liq ACUCANTIDAD3 ON ACUCANTIDAD3.alcant = ACUCANTIDAD3.alcant
JOIN 
    acu_liq ACUMONTO1 ON ACUMONTO1.almonto = ACUMONTO1.almonto
JOIN 
    acu_liq ACUMONTO2 ON ACUMONTO2.almonto = ACUMONTO2.almonto
JOIN 
    acu_liq ACUMONTO3 ON ACUMONTO3.almonto = ACUMONTO3.almonto;
